package com.herosandwich.controller;

public enum Action {
    MOVE_NORTH,
    MOVE_NORTH_EAST,
    MOVE_SOUTH_EAST,
    MOVE_SOUTH,
    MOVE_SOUTH_WEST,
    MOVE_NORTH_WEST,
    ATTACK,
    BIND_WONDS,
    BARGAIN,
    OBSERVATION,
    OCCUPATION_SKILL_1,
    OCCUPATION_SKILL_2,
    OCCUPATION_SKILL_3,
    USE,
    SEARCH_MOVE_NORTH,
    SEARCH_MOVE_NORTH_EAST,
    SEARCH_MOVE_SOUTH_EAST,
    SEARCH_MOVE_SOUTH,
    SEARCH_MOVE_SOUTH_WEST,
    SEARCH_MOVE_NORTH_WEST,
    RANGED_ATTACK
}