package com.herosandwich.controller;

public enum Action {
    MOVE_NORTH,
    MOVE_NORTH_EAST,
    MOVE_SOUTH_EAST,
    MOVE_SOUTH,
    MOVE_SOUTH_WEST,
    MOVE_NORTH_WEST,
    SKILL1,
    SKILL2,
    SKILL3,
    SKILL4,
    USE,
    SEARCH_MOVE_NORTH,
    SEARCH_MOVE_NORTH_EAST,
    SEARCH_MOVE_SOUTH_EAST,
    SEARCH_MOVE_SOUTH,
    SEARCH_MOVE_SOUTH_WEST,
    SEARCH_MOVE_NORTH_WEST,
}